import {NextResponse} from "next/server";import {requireUser} from "@/lib/auth";import {quoteSchema} from "@/lib/validation";
export async function POST(req:Request){try{const {supabase,user}=await requireUser();const body=quoteSchema.parse(await req.json());const {data:m}=await supabase.from("organization_members").select("organization_id,role").eq("user_id",user.id).eq("status","active").limit(1).maybeSingle();if(!m||!["owner","admin","manager","member"].includes(m.role))return NextResponse.json({error:"Forbidden"},{status:403});
const customer=await supabase.from("customers").select("id").eq("id",body.customerId).eq("organization_id",m.organization_id).maybeSingle();if(!customer.data)return NextResponse.json({error:"Customer not found"},{status:404});
const total=body.items.reduce((sum,item)=>sum+(item.quantity*item.unitPriceCents),0);
const quote=await supabase.from("quotes").insert({organization_id:m.organization_id,customer_id:body.customerId,title:body.title,notes:body.notes||null,status:"draft",subtotal_cents:total,tax_cents:0,total_cents:total,created_by:user.id}).select("id").single();if(quote.error)throw quote.error;
const rows=body.items.map(item=>({quote_id:quote.data.id,organization_id:m.organization_id,service_id:item.serviceId,description:item.description,quantity:item.quantity,unit_price_cents:item.unitPriceCents,line_total_cents:item.quantity*item.unitPriceCents}));
const itemResult=await supabase.from("quote_items").insert(rows);if(itemResult.error){await supabase.from("quotes").delete().eq("id",quote.data.id);throw itemResult.error}
await supabase.from("quote_versions").insert({quote_id:quote.data.id,organization_id:m.organization_id,version:1,snapshot:{title:body.title,notes:body.notes||null,items:rows,totalCents:total},created_by:user.id});
await supabase.from("audit_logs").insert({organization_id:m.organization_id,user_id:user.id,action:"quote.created",resource_type:"quote",resource_id:quote.data.id,metadata:{totalCents:total}});
return NextResponse.json({id:quote.data.id},{status:201})}catch(e:any){return NextResponse.json({error:e?.message==="UNAUTHENTICATED"?"Unauthorized":"Invalid quote request"},{status:e?.message==="UNAUTHENTICATED"?401:400})}}